{"name": "Тест получения заказа пользователя без авторизации", "status": "passed", "description": "Получение ошибки при попытке получить инфо о заказе без авторизации", "start": 1706703686896, "stop": 1706703687249, "uuid": "a1ecc035-d27a-4ec5-8e70-d142e2a3ea19", "historyId": "dc6b5b7f88d5637c7c3efcd603b1dc6b", "testCaseId": "dc6b5b7f88d5637c7c3efcd603b1dc6b", "fullName": "tests.test_api_get_user_orders.TestApiGetUserOrders#test_no_auth_user_get_user_order_error", "labels": [{"name": "feature", "value": "Проверка получения заказа конкретного пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_get_user_orders"}, {"name": "subSuite", "value": "TestApiGetUserOrders"}, {"name": "host", "value": "Redmi6-Redmi6"}, {"name": "thread", "value": "9770-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_get_user_orders"}]}